version: "3"

services:
  synesis-kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.0
    container_name: synesis-kibana
    restart: unless-stopped
    networks:
      - gerenciatec-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synesis.rule=Host(`syslog.${GTEC_DELEGATED_DOMAIN}`) || PathPrefix(`/syslog`)"
      - "traefik.http.routers.synesis.tls=true"
      - "traefik.http.routers.synesis.tls.certresolver=myresolver"
      - "traefik.http.routers.synesis.middlewares=synesis-stripprefix,synesis-auth"
      - "traefik.http.middlewares.synesis-stripprefix.stripprefix.prefixes=/syslog"
      - "traefik.http.middlewares.synesis-auth.basicauth.users=admin:$$apr1$$yDbQpTMi$$.WY390fKGUi./DBTogc1l/"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601

      TZ: "America/Sao_Paulo"

      SERVER_BASEPATH: "/synesis"

      KIBANA_INDEX: ".kibana-synlite"

      HOSTS: "http://elasticsearch:9200"

      KIBANA_DEFAULTAPPID: "dashboard/ec85a1c0-73e0-11e9-b45b-85d6db7c0cfc"

      LOGGING_QUIET: "true"

  synesis-kibana-init:
    image: hub.gerenciatec.com.br/synesis-kibana-init:latest
    container_name: synesis-kibana-init
    restart: "no"
    depends_on:
      - synesis-kibana
    networks:
      - gerenciatec-network

  synesis-logstash:
    image: robcowart/synlite-syslog-logstash-oss:1.1.0_7.0.1
    container_name: synesis-logstash
    restart: unless-stopped
    networks:
      - gerenciatec-network
    ports:
      - "514:51400/udp"
    environment:
      # JVM Heap size - this MUST be at least 512MB (1GB preferred)
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"

      TZ: "America/Sao_Paulo"

      # NOTE: Ports below 1024 require root privileges. Since Logstash will be started with the user 'logstash' we will listen on port 514.
      # The TCP port on which to listen for syslog messages.
      SYNLITE_SYSLOG_TCP_IPV4_PORT: 51400
      # The UDP port on which to listen for syslog messages.
      SYNLITE_SYSLOG_UDP_IPV4_PORT: 51400

      # The number of UDP input threads.
      SYNLITE_SYSLOG_UDP_WORKERS: 4
      # The number of unprocessed UDP packets the input can buffer.
      SYNLITE_SYSLOG_UDP_QUEUE_SIZE: 4096
      # The UDP socket receive buffer size (bytes).
      SYNLITE_SYSLOG_UDP_RCV_BUFF: 33554432

      # The Elasticsearch host to which the output will send data.
      SYNLITE_SYSLOG_ES_HOST: "elasticsearch:9200"
      # The username for the connection to Elasticsearch.
      SYNLITE_SYSLOG_ES_USER: "elastic"
      # The password for the connection to Elasticsearch.
      SYNLITE_SYSLOG_ES_PASSWORD: "changeme"

      # Enable/Disable DNS requests.
      SYNLITE_SYSLOG_RESOLVE_IP2HOST: "false"
      # The DNS server to which the dns filter should send requests.
      SYNLITE_SYSLOG_NAMESERVER: "127.0.0.1"
      # The cache size for successful DNS queries
      SYNLITE_SYSLOG_DNS_HIT_CACHE_SIZE: 10000
      # The time in seconds successful DNS queries are cached.
      SYNLITE_SYSLOG_DNS_HIT_CACHE_TTL: 900
      # The cache size for failed DNS queries.
      SYNLITE_SYSLOG_DNS_FAILED_CACHE_SIZE: 25000
      # The time in seconds failed DNS queries are cached
      SYNLITE_SYSLOG_DNS_FAILED_CACHE_TTL: 3600

      # Whether to use the timestamp from the received message to set @timestamp.
      SYNLITE_SYSLOG_MSG_TIMESTAMP: "true"
      # The timezone of the timestamp of the incoming messages.
      SYNLITE_SYSLOG_TZ: "America/Sao_Paulo"

  synesis-curator:
    image: hub.gerenciatec.com.br/curator:latest
    container_name: synesis-curator
    restart: unless-stopped
    networks:
      - gerenciatec-network
    environment:
      FILTERTYPE_PATTERN_VALUE: "syslog-"
      FILTERTYPE_AGE_UNIT_COUNT: 30

networks:
  gerenciatec-network:
    external: true
