version: "3"

services:
  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    restart: unless-stopped
    networks:
      - gerenciatec-network
    ports:
      - 80:80
      - 443:443
    command:
      - --api.dashboard=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/Sao_Paulo"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rproxy.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard/`)"
      - "traefik.http.services.rproxy.loadbalancer.server.port=8080"
      - "traefik.http.routers.rproxy.service=api@internal"
      - "traefik.http.routers.rproxy.middlewares=api-auth"
      - "traefik.http.middlewares.rproxy-auth.basicauth.users=gtec:$$apr1$$rkiK56dj$$z4GlaHm5DRiEMGMUpNVAr1"

networks:
  gerenciatec-network:
    external: true
