version: "3"

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:latest
    container_name: reverse-proxy
    restart: unless-stopped
    networks:
      - gerenciatec-network
    ports:
      - 80:80
      - 443:443
    command:
      - --api.dashboard=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/Sao_Paulo"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard/`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=api-auth"
      - "traefik.http.middlewares.api-auth.basicauth.users={$DASHBOARD_AUTHENTICATION}"

networks:
  gerenciatec-network:
    external: true
