version: "3"

services:
  elastiflow-kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.5.0
    container_name: elastiflow-kibana
    restart: unless-stopped
    networks:
      - gerenciatec-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elastiflow.rule=Host(`flow.${LOCAL_DOMAIN}`) || PathPrefix(`/flow`)"
      - "traefik.http.routers.elastiflow.tls=true"
      - "traefik.http.routers.elastiflow.tls.certresolver=myresolver"
      - "traefik.http.routers.elastiflow.middlewares=elastiflow-stripprefix,elastiflow-auth"
      - "traefik.http.middlewares.elastiflow-stripprefix.stripprefix.prefixes=/elastiflow"
      - "traefik.http.middlewares.elastiflow-auth.basicauth.users=gtec:$$apr1$$Iqe9MT.2$$RaZP0TTtIcAIGNXsbohnB."
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601

      TZ: "America/Sao_Paulo"

      SERVER_BASEPATH: "/elastiflow"

      KIBANA_INDEX: ".kibana-elastiflow"

      HOSTS: "http://elasticsearch:9200"

      KIBANA_DEFAULTAPPID: "dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5"

      LOGGING_QUIET: "true"

  elastiflow-kibana-init:
    image: hub.gerenciatec.com.br/elastiflow-kibana-init:latest
    container_name: elastiflow-kibana-init
    restart: "no"
    depends_on:
      - elastiflow-kibana
    networks:
      - gerenciatec-network

  elastiflow-logstash:
    image: robcowart/elastiflow-logstash-oss:3.5.3
    container_name: elastiflow-logstash
    restart: unless-stopped
    networks:
      - gerenciatec-network
    ports:
      - 2055:2055/udp
      - 6343:6343/udp
      - 4739:4739/udp
      - 4739:4739
    environment:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: "-Xms4g -Xmx4g"

      ELASTIFLOW_ES_HOST: "http://elasticsearch:9200"

      TZ: "America/Sao_Paulo"

      # ElastiFlow global configuration
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"

      # Name resolution option
      ELASTIFLOW_RESOLVE_IP2HOST: "false"
      ELASTIFLOW_NAMESERVER: "127.0.0.1"

      ELASTIFLOW_NETFLOW_IPV4_PORT: 2055
      ELASTIFLOW_SFLOW_IPV4_PORT: 6343
      ELASTIFLOW_IPFIX_TCP_IPV4_PORT: 4739

  elastiflow-curator:
    image: hub.gerenciatec.com.br/curator:latest
    container_name: elastiflow-curator
    restart: unless-stopped
    networks:
      - gerenciatec-network
    environment:
      FILTERTYPE_PATTERN_VALUE: "elastiflow-"

networks:
  gerenciatec-network:
    external: true
